Features/us 13 filter compenents
WildCodeSchool/nts-js-202009-p2-herbier pull request #34
Opened 2020-11-05 16:06 UTC by rouxxi

add some selector filter almost fonctionnal !!

2020-11-05 17:31 UTC, NicolasBonamy requested changes

2020-11-05 17:31 UTC, NicolasBonamy commented on src/components/DataBase.jsx
> +<<<<<<< HEAD
Conflit à régler

2020-11-05 17:31 UTC, NicolasBonamy commented on src/components/DataBase.jsx
> +=======
Conflit à régler

2020-11-05 17:31 UTC, NicolasBonamy commented on src/components/DataBase.jsx
> +>>>>>>> 06b64d4fa2b659801780c04eb53347e8ab1d9650
Conflit à régler

2020-11-05 17:31 UTC, NicolasBonamy commented on src/components/Library.jsx
> +>>>>>>> 06b64d4fa2b659801780c04eb53347e8ab1d9650
Conflit à régler

2020-11-05 17:31 UTC, NicolasBonamy commented on src/components/Library.jsx
> +      scannedLybrary: [
scannedLibrary

2020-11-06 08:32 UTC, rouxxi reviewed
delete conflic

2020-11-06 08:37 UTC, rouxxi reviewed
did some correction conflict

2020-11-06 08:50 UTC, NicolasBonamy approved these changes

2020-11-06 09:10 UTC, bastienwcs approved these changes

2020-11-06 09:19 UTC, merged